colorscheme desertex

set-option global tabstop 2
set-option global indentwidth 2
set-option global scrolloff 5,1
set-option global grepcmd 'rg --column'
set-option global completers filename word=all
set-option global autoinfo normal|command|onkey
set-option -add global matching_pairs ‹ › « » “ ” ‘ ’
set-option -add global ui_options ncurses_assistant=none ncurses_change_colors=true

add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap
add-highlighter global/ show-matching
