#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

# Run polybar
cd ${SCRIPTPATH}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor
do 
  monitor=$monitor polybar -c config.ini main &> /dev/null &
done

# Start my apps
/usr/bin/sh -c /home/alcadramin/.config/xrandr.sh
picom -b --experimental-backends
xfce4-power-manager
numlockx on &
nitrogen --restore &
parcellite &
/usr/libexec/polkit-gnome-authentication-agent-1 &
/usr/libexec/xfce4/notifyd/xfce4-notifyd &
/usr/bin/emacs --daemon &

